name: Codespell
on:
  push:
    tags:
      - v*
    branches:
      - master
      - release-*
  pull_request:

# cancel the in-progress workflow when PR is refreshed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  codespell:
    name: codespell
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: codespell
        uses: codespell-project/actions-codespell@master
        with:
          skip: logo.svg,*.sum
          check_filenames: true
          check_hidden: true
