name: Release Plugin
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  Release-Plugin-At-Krew-Index:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: setup golang
        uses: ./.github/workflows/set-up-go

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # krew-release-bot is a bot that automates the update of plugin manifests in krew-index when a new version of your kubectl plugin is released.
      # https://github.com/rajatjindal/krew-release-bot
      - name: Update new version in krew-index
        uses: rajatjindal/krew-release-bot@v0.0.47
