name: ShellCheck
on:
  pull_request:

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          severity: warning
          check_together: "yes"
          disable_matcher: false
          format: gcc
